name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'          

      - name: Initialze codeql
        uses: github/codeql-action/init@v3
        with:
          languages: java-kotlin
          queries: security-extended
      
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3 
  
  build:
    runs-on: ubuntu-latest
    needs: [codeql]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

    - name: Build with Maven and Run Checkstyle
      # The 'verify' phase will compile, test, and package the code.
      # The 'site' phase will generate the Checkstyle report.
      run: mvn -B clean verify site
